name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install
    - name: Submit dependency graph
      uses: github/action-graph-reporter@v1
    - name: Generate Java coverage report
      run: |
        mvn test jacoco:report
    - name: Upload Java coverage report
      uses: codecov-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        file: target/site/jacoco/jacoco.xml
